services: docker
  - docker

before_install:
  - echor ${DOCKER_PASSWORD} | docker login -u $DOCKER_USERNAME --password-stdin
  - docker build . --target devenv -t ronualdo/peste:${TRAVIS_COMMIT}

script:
  - docker run ronualdo/peste:${TRAVIS_COMMIT} mix test
  - docker push ronualdo/peste:${TRAVIS_COMMIT}
