services: docker
  - docker

before_install:
  - echo ${DOCKER_PASSWORD} | docker login -u $DOCKER_USERNAME --password-stdin
  - docker build . --target devenv -t ci-env

script:
  - docker run ci-env mix test
  - docker build . -t ronualdo/peste:${TRAVIS_COMMIT}
  - docker push ronualdo/peste:${TRAVIS_COMMIT}
