services: docker
  - docker

before_install:
  - docker build . --target detenv -t peste:${TRAVIS_COMMIT}

script:
  - docker run peste:${TRAVIS_COMMIT} mix test
  - docker push ronualdo/peste:${TRAVIS_COMMIT}
