version: "3.7"
services:
  peste_api:
    build:
      context: .
      target: devenv
    ports:
      - "4444:4000"
    dns:
      - 8.8.8.8
    environment:
      TEST_CHAT_ID: ${TEST_CHAT_ID}
      TEST_TOKEN: ${TEST_TOKEN}
      PESTE_BOT_TOKEN: ${PESTE_BOT_TOKEN}
    command: /bin/sh -c "mix deps.get && mix phx.server"
    volumes:
      - ./apps:/apps

