apiVersion: apps/v1
kind: Deployment
metadata:
  name: peste-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peste-api
  template:
    metadata:
      labels:
        app: peste-api
    spec:
      containers:
      - name: peste-api
        image: ronualdo/peste:60bda92ed50cb5e74378ba5b8ae42e86ba6fb3e3
        ports:
          - containerPort: 4000
        env:
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: peste-secrets
                key: secret-key-base
          - name: PESTE_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: peste-secrets
                key: peste-bot-token


